hello:
	gcc -o hello-world hello-world.c -lcs50 
compare:
	gcc -o compare compare.c -lcs50 
agree:
	gcc -o agree agree.c -lcs50 
meow:
	gcc -o meow meow.c -lcs50 
calculator:
	gcc -o calculator calculator.c -lcs50 
mario:
	gcc -o mario mario.c -lcs50 

